// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dreuzLhxsirEjBh43g-P5eKryXJAMd8',
    appId: '1:897753127617:web:5a99e05016278d09de9240',
    messagingSenderId: '897753127617',
    projectId: 'cartelera-a1e1c',
    authDomain: 'cartelera-a1e1c.firebaseapp.com',
    storageBucket: 'cartelera-a1e1c.firebasestorage.app',
    measurementId: 'G-XW6LN4J0KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4EDAIUM-UHACzVOftmaX02fGF1RyoRlU',
    appId: '1:897753127617:android:02c93bb5bbbb142ade9240',
    messagingSenderId: '897753127617',
    projectId: 'cartelera-a1e1c',
    storageBucket: 'cartelera-a1e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jNOCTzYAsInBvw7weVIBuausJeH89zE',
    appId: '1:897753127617:ios:b9edaec42351e522de9240',
    messagingSenderId: '897753127617',
    projectId: 'cartelera-a1e1c',
    storageBucket: 'cartelera-a1e1c.firebasestorage.app',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2jNOCTzYAsInBvw7weVIBuausJeH89zE',
    appId: '1:897753127617:ios:b9edaec42351e522de9240',
    messagingSenderId: '897753127617',
    projectId: 'cartelera-a1e1c',
    storageBucket: 'cartelera-a1e1c.firebasestorage.app',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1dreuzLhxsirEjBh43g-P5eKryXJAMd8',
    appId: '1:897753127617:web:0681551f3b652c95de9240',
    messagingSenderId: '897753127617',
    projectId: 'cartelera-a1e1c',
    authDomain: 'cartelera-a1e1c.firebaseapp.com',
    storageBucket: 'cartelera-a1e1c.firebasestorage.app',
    measurementId: 'G-TTMLT7SJ9Y',
  );

}